# Generated by Django 3.0.6 on 2020-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_cargo_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='descricaCargo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='descricaoDep',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
