# Generated by Django 3.0.6 on 2020-06-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200607_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='descricaCargo',
            new_name='descricaoCargo',
        ),
    ]
